#!/usr/bin/env python3
"""Everything about this suite that would otherwise fail silently.

Run at image-build time, so a suite that cannot grade correctly fails the build
rather than producing a confident wrong number at grading time.  Four things,
each of which has a failure mode that looks like success:

``the recording loads``
    ``load_golden`` verifies a fingerprint over the whole capture.  A recording
    regenerated by hand, or truncated in transit, is not the one these assertions
    were written against -- and every comparison against it would still *run*.

``routing.self_check``
    Every recorded case is graded by exactly one module, and every module's
    session list is the one its cases imply.  An unclaimed case is a hole: 612
    cases are what the stage promises, and a case no module owns is simply not
    graded.  An empty module is worse than a hole, because it carries weight and
    contributes a vacuous 100% to the stage rate.

``battery.self_check``
    A module imports a battery if and only if it has cases on that battery's axis.
    The expensive direction is importing one it has no cases for: the
    parametrisation collects empty, and an empty collection scores as a miss, so
    the module silently loses score for a surface that was never broken.

``the manifest``
    suite.toml is the file most likely to be edited and least likely to be tested.
    A duplicate id, a weight that is not a number, or a module directory that does
    not exist should fail here rather than half-way through a grading run.

Exit status is the number of problems found, capped at 1, so it reads as a plain
pass/fail to `set -e`.  Every problem is printed; the point is to fix them all in
one pass rather than one per rebuild.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SUITE = HERE.parent
sys.path.insert(0, str(HERE))

import battery                                                   # noqa: E402
import replay                                                    # noqa: E402
import routing                                                   # noqa: E402


def main() -> int:
    failures = 0

    golden = replay.load_golden()
    summary = golden.get("summary") or {}
    print(f"recording: fingerprint verified, {len(golden.get('sessions') or {})} "
          f"sessions, {len(golden.get('cli') or {})} CLI invocations"
          + (f", {summary.get('cases')} cases" if summary.get("cases") else "")
          + f", captured over {golden.get('passes')} passes")

    if routing.self_check() != 0:
        failures += 1

    problems = battery.self_check(SUITE / "modules", golden)
    if problems:
        print("\nFAIL: module/axis mismatch")
        for problem in problems:
            print("  - " + problem)
        failures += 1
    else:
        print("batteries: every module grades exactly the axes it has cases on")

    manifest = SUITE / "suite.toml"
    try:
        from swerefactor import config

        suite = config.Suite.load(manifest)
        missing = [m.id for m in suite.modules if not (suite.root / m.dir).is_dir()]
        if missing:
            print(f"\nFAIL: suite.toml names missing module dir(s): {missing}")
            failures += 1
        else:
            print(f"manifest: {len(suite.modules)} modules, "
                  f"weight {suite.weight_total:g}")
    except ImportError:
        # The harness is only on PYTHONPATH inside the image.  Running this from a
        # checkout is still useful for the other three checks, so say what was
        # skipped rather than failing on an absence that is expected there.
        print("manifest: skipped, swerefactor is not importable here")

    if failures:
        print(f"\n{failures} self-check(s) failed", file=sys.stderr)
        return 1
    print("\nself-check: this suite can grade")
    return 0


if __name__ == "__main__":
    sys.exit(main())
