"""Running the corpus against both sides once, and publishing the result.

This is the expensive part of the stage: two servers, two profiles each, a graph
import and a CH/LM preparation per launch.  Doing that per module would multiply
it by the number of modules that need it, so it happens exactly once — in the
`build` module, which suite.toml declares first and required — and every later
module restores the capture from $SRB_SUITE_WORK instead of repeating it.

That is safe because the runner executes modules strictly sequentially, in
declaration order, each in its own process group.  It is not a race; it is a
ledger with one writer that runs to completion before the first reader starts.

Each case is asked TWICE per side.  That is what makes volatility measurable
instead of declared — see harness/normalize.py.  The cost is one extra HTTP
round trip per case against an already-warm server, which is nothing next to the
import.
"""
from __future__ import annotations

import base64
import json
import os
import time
from pathlib import Path

from . import corpus, normalize, server, wire

CAPTURE_NAME = "capture.json"


def work_dir() -> Path:
    """The suite's shared scratch directory.

    $SRB_SUITE_WORK is set by the runner and shared by every module in the
    suite.  Falling back to a fixed path rather than a temp dir: a fallback that
    varied per process would make the ledger unfindable by the readers, and a
    silent re-capture per module would turn a 20-minute stage into hours.
    """
    return Path(os.environ.get("SRB_SUITE_WORK", "/tmp/srb-fw07-suite"))


def capture_path() -> Path:
    return work_dir() / CAPTURE_NAME


# --- serialisation -----------------------------------------------------------
# Bodies are base64 in the ledger.  Not for size: a route response is mostly
# ASCII and would survive being stored as text.  For fidelity — a protobuf tile
# and a gzipped body are not valid UTF-8, and a ledger that stored them with
# errors="replace" would compare two mangled bodies and call them equal.

def _enc(b: bytes) -> str:
    return base64.b64encode(b).decode("ascii")


def _dec(s: str) -> bytes:
    return base64.b64decode(s.encode("ascii"))


def _record(resp: wire.Response) -> dict:
    return {
        "status": resp.status,
        "headers": [[k, v] for k, v in resp.headers],
        "body_b64": _enc(resp.body),
    }


def _restore(d: dict) -> wire.Response:
    return wire.Response(d["status"], "", [(k, v) for k, v in d["headers"]],
                         _dec(d["body_b64"]))


# --- asking ------------------------------------------------------------------

def _resolve_body(case: dict, data_dir: Path):
    """A body that starts with '@' names a committed fixture file.

    Fixtures rather than generated bytes, so that both sides are asked about
    identical input and the input is reviewable in the repository.
    """
    body = case["body"]
    if isinstance(body, str) and body.startswith("@"):
        return (data_dir / "bodies" / body[1:]).read_bytes()
    if isinstance(body, str):
        return body.encode()
    return body


def ask_side(srv: server.Server, cases: list[dict], data_dir: Path,
             repeats: int = 2) -> dict:
    """Ask every case `repeats` times against one running server.

    A failure to get any answer at all is recorded as a transport error rather
    than raised: one endpoint that hangs should cost the cases that touch it, not
    abort the capture and zero every module in the suite.
    """
    out: dict[str, list] = {}
    for case in cases:
        body = _resolve_body(case, data_dir)
        answers = []
        for _ in range(repeats):
            transport = srv.transport(case["port"])
            try:
                resp = transport.send(case["method"], case["target"],
                                      case["headers"], body)
                answers.append(_record(resp))
            except Exception as exc:            # noqa: BLE001 - reported, not raised
                answers.append({"error": f"{type(exc).__name__}: {exc}"})
        out[case["id"]] = answers
    return out


def _side_volatility(answers: list) -> dict:
    """Measured volatility for one case on one side, in the ledger's shape.

    What counts as volatile is normalize.body_volatility's decision; this only
    unwraps the two recorded answers and writes the paths as JSON lists.
    """
    if len(answers) < 2 or any("error" in a for a in answers):
        return {"paths": [], "unstable_bytes": False}
    vol = normalize.body_volatility(_dec(answers[0]["body_b64"]),
                                    _dec(answers[1]["body_b64"]))
    return {"paths": [list(p) for p in
                      sorted(vol["paths"], key=lambda t: tuple(map(str, t)))],
            "unstable_bytes": vol["unstable_bytes"]}


def build_capture(reference: dict, submission: dict, cases: list[dict],
                  meta: dict) -> dict:
    doc = {
        "corpus_fingerprint": corpus.fingerprint(),
        "captured_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "meta": meta,
        "cases": {},
    }
    for case in cases:
        cid = case["id"]
        ref = reference.get(cid, [])
        sub = submission.get(cid, [])
        doc["cases"][cid] = {
            "suite": case["suite"],
            "profile": case["profile"],
            "port": case["port"],
            "body_mode": case["body_mode"],
            "why": case["why"],
            "reference": ref,
            "submission": sub,
            "reference_volatility": _side_volatility(ref),
            "submission_volatility": _side_volatility(sub),
        }
    return doc


def write(doc: dict) -> Path:
    p = capture_path()
    p.parent.mkdir(parents=True, exist_ok=True)
    tmp = p.with_suffix(".json.tmp")
    tmp.write_text(json.dumps(doc, indent=1, sort_keys=True))
    tmp.replace(p)          # atomic: a reader never sees a half-written ledger
    return p


def load() -> dict:
    p = capture_path()
    if not p.exists():
        raise RuntimeError(
            f"no capture at {p}.  The `build` module publishes it and is "
            f"declared first and required in suite.toml; if it failed, every "
            f"module after it has nothing to compare and this is the symptom.")
    doc = json.loads(p.read_text())
    got = doc.get("corpus_fingerprint")
    want = corpus.fingerprint()
    if got != want:
        raise RuntimeError(
            f"the capture was taken against corpus {got}, this process has "
            f"corpus {want}.  Two different corpora in one suite run means the "
            f"image is inconsistent with itself.")
    return doc


def authorities(doc: dict, entry: dict) -> tuple[int, int] | None:
    """The (reference, submission) port this case was actually reached on.

    Read out of the ledger's own meta rather than imported from the build module:
    the ports that matter are the ones the capture was taken with, and a constant
    imported here would keep agreeing with itself after they changed.  None if the
    ledger does not record them, which leaves the authority unfolded and compared
    — the safe direction, and visible as a failure rather than as a silent pass.
    """
    ports = (doc.get("meta") or {}).get("ports") or {}
    try:
        return (int(ports["reference"][entry["port"]]),
                int(ports["submission"][entry["port"]]))
    except (KeyError, TypeError, ValueError):
        return None


def case_pair(doc: dict, cid: str):
    """The reference and submission answers for one case, plus its volatility.

    Returns (ref_response, sub_response, masked_paths, entry, authorities) with
    responses as wire.Response, or raises with the transport error if either side
    never answered.
    """
    entry = doc["cases"].get(cid)
    if entry is None:
        raise RuntimeError(f"case {cid} is not in the capture")
    for side in ("reference", "submission"):
        answers = entry[side]
        if not answers:
            raise RuntimeError(f"{cid}: the {side} produced no answer at all")
        if "error" in answers[0]:
            raise RuntimeError(f"{cid}: the {side} could not be reached: "
                               f"{answers[0]['error']}")
    masked = {tuple(p) for p in entry["reference_volatility"]["paths"]}
    masked |= {tuple(p) for p in entry["submission_volatility"]["paths"]}
    return (_restore(entry["reference"][0]), _restore(entry["submission"][0]),
            masked, entry, authorities(doc, entry))
