#!/usr/bin/env python3
"""The Autotools build system has left the source tree.

Contract §2. Every check here reads the delivered tree and nothing else -- it
does not configure, does not build, and could not: this image has no CMake and no
compiler.

They are all advisory, including the file-absence ones, and the reason is worth
stating because "advisory" reads like "weakened". The gate this stage answers is
`autotools_retired`, and its question is not "does `configure.ac` exist" -- it is
whether the old build system is *gone* rather than renamed. A submission that
deletes `configure.ac` and adds `cmake/legacy-configure.sh.in` containing the same
content passes every absence check in this file and fails the gate. The absence
checks are how the reviewer finds the easy half quickly, and
`scoring.grade_audit` gates on the reviewer's answer.

What is deliberately *not* here: a pattern deciding whether a build file "reaches
for the Autotools toolchain". It could not tell `# we used to run autoreconf` from
a target that runs it, nor a `configure_file()` from a `./configure`, and a
migration that renames its wrapper would defeat it while a comment tripped it.
That question needs a reader, and has one.
"""

from __future__ import annotations

import os
import re
from pathlib import Path

import pytest

import srbscan

pytestmark = pytest.mark.scan

DELETED_FILES = [
    "autogen.sh",
    "configure.ac",
    "Makefile.am",
    "src/Makefile.am",
    "src/libsodium/Makefile.am",
    "src/libsodium/include/Makefile.am",
    "test/Makefile.am",
    "test/default/Makefile.am",
    "libsodium.pc.in",
    "libsodium-uninstalled.pc.in",
]

DELETED_DIRS = ["m4", "build-aux", "autom4te.cache"]

# Autotools output a State-A build may have left behind.
STALE_OUTPUT = [
    "configure", "aclocal.m4", "config.status", "config.log", "libtool",
    "Makefile.in", "src/Makefile.in", "src/libsodium/Makefile.in",
    "src/libsodium/include/Makefile.in", "test/Makefile.in",
    "test/default/Makefile.in", "compile", "depcomp", "install-sh",
    "missing", "test-driver", "ltmain.sh", "config.guess", "config.sub",
]

PRESERVED = ["README.markdown", "LICENSE", "AUTHORS", "ChangeLog", "THANKS",
             "src/libsodium/include/sodium/version.h.in"]

#: The Autoconf banner, as it appears in the first few KiB of a generated
#: `configure`. A file that carries this *is* generated Autotools output no matter
#: what it has been renamed to, which is why this one check is a content match
#: rather than a name match.
AUTOCONF_BANNER = re.compile(
    r"Generated by GNU Autoconf|# Guess values for system-dependent variables|"
    r"autoconf \(GNU Autoconf\)")


@pytest.mark.parametrize("relpath", DELETED_FILES)
def test_autotools_file_deleted(repo, relpath):
    p = repo / relpath
    assert not p.exists(), (
        f"{relpath} is still in the tree; §2 requires the Autotools build "
        f"system to be removed, not left beside the CMake one")


@pytest.mark.parametrize("reldir", DELETED_DIRS)
def test_autotools_dir_deleted(repo, reldir):
    p = repo / reldir
    if not p.exists():
        return
    contents = srbscan.rel_files(p)[:10]
    pytest.fail(
        f"{reldir}/ is still in the tree with {len(contents)} file(s): "
        f"{contents}")


@pytest.mark.parametrize("relpath", STALE_OUTPUT)
def test_stale_autotools_output_absent(repo, relpath):
    p = repo / relpath
    assert not p.exists(), (
        f"{relpath} is generated Autotools output left in the delivered tree")


def test_no_makefile_am_anywhere(repo, delivered_files):
    found = [r for r in delivered_files if os.path.basename(r) == "Makefile.am"]
    assert not found, f"Makefile.am survives at: {found}"


def test_no_makefile_in_anywhere(repo, delivered_files):
    found = [r for r in delivered_files if os.path.basename(r) == "Makefile.in"]
    assert not found, f"Makefile.in survives at: {found}"


def test_no_m4_macro_files(repo, delivered_files):
    found = [r for r in delivered_files if r.endswith(".m4")]
    assert not found, (
        f"Autoconf macro files survive at: {found[:10]}; the feature detection "
        f"has to be expressed in CMake, not carried along in m4")


def test_no_libtool_archives(repo, delivered_files):
    found = [r for r in delivered_files if r.endswith(".la") or r.endswith(".lo")]
    assert not found, f"libtool artefacts survive at: {found[:10]}"


def test_pc_in_templates_are_wired_into_the_build(repo, delivered_files):
    """A surviving `.pc.in` has to be one the CMake build uses.

    Not one that has to be absent. `.pc.in` is a pkg-config substitution template,
    not an Autotools one, and `configure_file(foo.pc.in foo.pc @ONLY)` is the
    canonical way a CMake project generates it -- so a check that condemned every
    `.pc.in` would condemn the idiomatic migration. The two State A templates
    being gone from their own paths is already required by
    `test_autotools_file_deleted`, which lists both.

    What is worth asking instead: a template nothing references is a dead file
    carried along. Stage 2 measures the installed `.pc` and its contents; this is
    about whether the template is live.
    """
    found = [r for r in delivered_files if r.endswith(".pc.in")]
    if not found:
        pytest.skip("no .pc.in templates in the delivered tree")

    referenced = []
    for path, rel in srbscan.build_files(repo):
        text = srbscan.read(path)
        if not text:
            continue
        for tmpl in found:
            if tmpl in text or os.path.basename(tmpl) in text:
                referenced.append(tmpl)
    orphans = sorted(set(found) - set(referenced))
    assert not orphans, (
        f"pkg-config template(s) delivered that no build file mentions: "
        f"{orphans}. A live template is configure_file()'d by the build; one "
        f"nothing references is a leftover")


@pytest.mark.parametrize("relpath", PRESERVED)
def test_preserved_file_still_present(repo, relpath):
    """The migration removes a build system, not the project.

    `version.h.in` is on this list for a specific reason: it is a template, it
    looks like Autotools output, and deleting it is a plausible over-correction.
    CMake has to keep substituting it -- stage 2 checks the installed
    `sodium/version.h` that comes out.
    """
    assert (repo / relpath).exists(), (
        f"{relpath} was removed; §2 retires the build system, and this is not "
        f"part of it")


def test_top_level_cmakelists_exists(repo):
    assert (repo / "CMakeLists.txt").is_file(), (
        "there is no CMakeLists.txt at the top of the tree, so there is no "
        "CMake build system to grade")


def test_cmake_minimum_required_is_320_or_newer(repo):
    """A floor, not a preference: the task text names 3.20 as the target.

    Read out of the submission's own `cmake_minimum_required`, so a project that
    asks for 3.25 passes. What fails is one that declares 3.5 and then relies on
    3.20 behaviour, which works on the grader's CMake and breaks on the version
    it advertises.
    """
    text = srbscan.read(repo / "CMakeLists.txt")
    m = re.search(r"cmake_minimum_required\s*\(\s*VERSION\s+(\d+)\.(\d+)",
                  text, re.I)
    assert m, (
        "CMakeLists.txt does not call cmake_minimum_required(VERSION ...); "
        "CMake warns and the policy set is then whatever the grader's CMake "
        "defaults to")
    major, minor = int(m.group(1)), int(m.group(2))
    assert (major, minor) >= (3, 20), (
        f"CMakeLists.txt declares cmake_minimum_required(VERSION "
        f"{major}.{minor}), below the 3.20 this task targets")


def test_no_configure_script_delivered(repo, delivered_files):
    """Generated Autoconf output, found by its banner rather than its name.

    The name check is `test_stale_autotools_output_absent`, and renaming defeats
    it. This one opens every delivered text file's first 4 KiB and looks for the
    banner Autoconf writes into what it generates, so `configure.sh`,
    `bootstrap`, or `cmake/legacy.in` are all caught by the same check.
    """
    hits = []
    for path, rel in srbscan.text_files(repo):
        head = srbscan.read_bytes(path, 4096).decode("utf-8", "replace")
        if AUTOCONF_BANNER.search(head):
            hits.append(rel)
    assert not hits, (
        f"these delivered files carry the GNU Autoconf generation banner, so "
        f"they are generated Autotools output whatever they are called: {hits}")


def test_no_autotools_cache_directories(repo, delivered_files):
    bad = [r for r in delivered_files
           if r.startswith(("autom4te.cache/", ".deps/", ".libs/"))
           or "/.deps/" in r or "/.libs/" in r]
    assert not bad, (
        f"Autotools/libtool build state survives at: {bad[:10]}")
